import { Injectable } from '@nestjs/common';
import { Task, TaskStatus } from './tasks.model';
import {v4 as uuid} from 'uuid';
import { CreateTaskDto } from './dto/create-task.dto';

/*  
    Generated by running the following command:
        nest g service tasks --no-spec
*/

@Injectable()
export class TasksService {
   private tasks:Task[] = [];
   
   //exposing a set of methods that will help the controller interface with the service is best practice. Rather than making the 
   //tasks array publid.
   getAllTasks(): Task[] {
    return this.tasks;
   }

   createTask(createTaskDto:CreateTaskDto): Task{
    //destructure createTaskDto
    const { title, description } = createTaskDto;
    console.log(`title = ${title} description=${description}`);
    const task: Task = {
        id: uuid(), 
        title, 
        description, 
        status: TaskStatus.OPEN,    
    };
    this.tasks.push(task);
    return task; 
   }
}
