import { Body, Controller, Get, Post } from '@nestjs/common';
import { CreateTaskDto } from './dto/create-task.dto';
import { Task } from './tasks.model';
import { TasksService } from './tasks.service';
/* eslint-disable */
/*
    Generated by running the following command:
        nest g controller tasks --no-spec
*/
@Controller('tasks')
export class TasksController {
  // tasksService: TasksService;
  //This will inject TasksService into this controller
  constructor(private tasksService: TasksService) {
    // this.tasksService.doSomething();
  }

  @Get()
  getAllTasks() {
    return this.tasksService.getAllTasks();
  }

  // @Post()
  // createTask(@Body() body){
  //   console.log('body', body);
  // }

  @Post()
  createTask(@Body() createTaskDto: CreateTaskDto): Task {
    return this.tasksService.createTask(createTaskDto);
  }

}
